### PR TITLE
add Drupal site to test against

### PR DESCRIPTION
**Pull request by alexfinnarn**
now that's a lot of files...I suppose the Drupal scaffolding could be created in the GH action/workflow, but then locally you'd have to do that each time or put more paths in `.gitignore` to reduce the number of files needed...Drupal is yuuuuge.

### CODE REVIEW

**Comment by alexfinnarn** [comment]
@dmundra Any thoughts on this PR? I suppose it could be done in a way where the Drupal site is created in the GH Workflow vs. committing all the files...but at least this is a working example.

For example, maybe there could be a step to `composer create-project drupal/recommended-project` and such before https://github.com/CivicActions/cypress-tests/pull/51/files#diff-5da9a41590fb261de0e464c95862528100c42c77dffad53b7c6de228b6afd2bdR28 ...

**Review by dmundra — COMMENTED** [review]
@alexfinnarn looks great. Ya I was wondering about adding all the files as it would be much lighter weight. It would be like the take-home repo. I would vote for that if you were up for reducing this PR.

**Comment by alexfinnarn** [comment]
@dmundra Even though the status check UI says it's still waiting, the Cypress tests pass in https://github.com/CivicActions/cypress-tests/actions/runs/4579068445/jobs/8086427275

**Review by dmundra — APPROVED** [review]
Looks good. Thank you!

**Comment by dmundra** [comment]
@alexfinnarn you might need to close and re-open to re-run the checks.

**Pull request merged**
