### PR TITLE
CKEditor tests

### LINKED ISSUE #43: Add a running example of iframe testing with Cypress
Maybe submodule this ckeditor demo https://github.com/ckeditor/ckeditor5-demos/tree/master/feature-rich and then write tests that interact with it?

### PR DESCRIPTION
**Pull request by dmundra**
Changes:

* For the CKEditor media tests, I had to enable the media modules and configure the button to be available on the 'Full HTML' toolbar. To do that I captured the Drupal config in code (that is most of the new files in this commit) and update the script to use that config (with a copy command) when spinning up the site. Had to switch the Drupal build to minimal profile to make it work with the `--existing-config` flag. Did require solution from https://github.com/cypress-io/cypress/issues/26155 to work with CKEditor.
* Added `cypress-real-events` and `cypress-file-upload` plugins.
* `cypress/e2e/3-civicactions-examples/drupal-ckeditor.cy.js` has CKEditor tests.
* Updated documentation and yarn.lock.

Closes #43

### CODE REVIEW

**Comment by alexfinnarn** [comment]
@dmundra I have a couple of comments on this PR...

> Did require solution from https://github.com/cypress-io/cypress/issues/26155 to work with CKEditor.

I feel like I had an issue with this but if I used https://github.com/dmtrKovalenko/cypress-real-events#cyrealtype I didn't seem to have an issue. Would using the "cypress-real-events" plugin make things easier? It's one of the plugins I was going to add at some point, and I think can be useful on a lot of projects.

> To do that I captured the Drupal config in code (that is most of the new files in this commit) and update the script to use that config (with a copy command) when spinning up the site.

At some point, I was going to add a custom module just for testing purposes where config could go related to any testing needs. Would it be a better idea to put the config in a module? 

For current project work, I am interested in providing partial config that merges into the existing config but so far have only imported whole config files. I'm not sure what the best method is to surgically "configure the button to be available on the 'Full HTML' toolbar" would be, but I'd hope an update hook or pieces of https://www.drupal.org/project/config_sync could be used so only the needed config is captured. 

Or maybe use a popular Drupal distribution/starter that would have more things configured than stock Drupal? I haven't kept up on this stuff but I bet there are `composer create` templates that might provide us with more things configured without us needing to capture the config.

**Comment by dmundra** [comment]
@alexfinnarn 

> I feel like I had an issue with this but if I used https://github.com/dmtrKovalenko/cypress-real-events#cyrealtype I didn't seem to have an issue. Would using the "cypress-real-events" plugin make things easier? It's one of the plugins I was going to add at some point, and I think can be useful on a lot of projects.

Good point. I avoid plugins but that one is handy for sure so I will add it.

> At some point, I was going to add a custom module just for testing purposes where config could go related to any testing needs. Would it be a better idea to put the config in a module?

I am not sure. In the take-home assignment we track the full config and that seems to work for that project and also easy to update in my mind as you just export and capture config changes.

> For current project work, I am interested in providing partial config that merges into the existing config but so far have only imported whole config files. I'm not sure what the best method is to surgically "configure the button to be available on the 'Full HTML' toolbar" would be, but I'd hope an update hook or pieces of https://www.drupal.org/project/config_sync could be used so only the needed config is captured.

Good question. To me that sounds more complicated than tracking the entire config but I am open to advice here.

> Or maybe use a popular Drupal distribution/starter that would have more things configured than stock Drupal? I haven't kept up on this stuff but I bet there are composer create templates that might provide us with more things configured without us needing to capture the config.

Should we like use the Umami demo? I again on the side of build our own config as needed and keep it up to date but for this project if a distribution gives us everything we would need then we can go with that.

**Comment by dmundra** [comment]
@alexfinnarn updated the CKEditor tests to use cypress-real-events plugin.

**Comment by dmundra** [comment]
Very cool @jonbot. Happy to help with that.

**Comment by dmundra** [comment]
@jonbot and @alexfinnarn added insert image tests and used the `cypress-file-upload` plugin to make way easier to upload a file: https://github.com/CivicActions/cypress-tests/pull/53/commits/925586b6c3d992c393dad90655bf2f3299b6e77d

**Review by alexfinnarn — APPROVED** [review]

**Pull request merged**
